accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path
from . import views

app_name='articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name='create'),
    path('article_details/<slug>', views.article_details, name="details")
]

djangonotes/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# import for media urls, settings for parameter
from django.conf.urls.static import static
from django.conf import settings

# import views from articles
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_list, name="home"),
    path('about/', views.about),
    
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.contrib.auth.models import User
from django.db import models

class Articles(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now=True)
    thumb=models.ImageField(default='default.png', blank=True)
    author=models.ForeignKey(User, default=None, on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+"..."

# To make migration file to track the change in models
#  python manage.py makemigrations
#  python manage.py migrate

articles/forms.py
from django.forms import ModelForm
from . import models

class CreateArticle(ModelForm):
    class Meta:
        model = models.Articles
        # field = '__all__' 
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect

def signup_view(request):
    if request.method=='POST':
        # req.POST is to acccess post data
        form=UserCreationForm(request.POST)
        # it validates the form --> is the username ok etc
        if form.is_valid():
            user = form.save()
            # log the user
            login(request, user)
            return redirect('articles:list')
    else:
        form=UserCreationForm()
    
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method=='POST':
        # data is not the 1st parameter of fn by default
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user
            user = form.get_user()
            login(request, user)
            #  if there is next query 
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect('articles:list')
    else:
        form=AuthenticationForm()
    
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Articles
from . import forms


def article_list(request):
    articles=Articles.objects.all().order_by('date')
    return render(request, "articles/articles_list.html", {'articles': articles})

def article_details(request, slug):
    # return HttpResponse(slug)
    article=Articles.objects.get(slug=slug)
    return render(request, "articles/article_details.html", {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form=forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            # commit=false to wait
            instance= form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form=forms.CreateArticle()
    return render(request, "articles/article_create.html", {'form' : form})

djangonotes/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Login</h2>
    <form  class="site-form" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %} 
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Signup">
    </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form action="/accounts/signup/" class="site-form" method="POST">
        {% csrf_token %} 
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock content %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
    <div class="create-article">
        <h2>Create an article</h2>
        {% comment %}  enctpe is ppty to add encryptn {% endcomment %}
        <form action="{% url 'articles:create' %}" class="site-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="{% static 'slugify.js' %}"></script>
{% endblock content %}

articles/templates/articles/article_details.html
{% extends 'base_layout.html'%}

{% block content %}
<div class="article-detail">
  <div class="article">
    {% comment %} url property is to get url of thumb {% endcomment %}
    <img src="{{ article.thumb.url }}">
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
  </div>
</div>
{% endblock content %}

articles/templates/articles/articles_list.html
{% extends 'base_layout.html'%} 
{% block content %}
  <h2>Article List</h2>
  <div class="articles">
    {% for article in articles %}
    <div class="article">
      <h2><a href="{% url 'articles:details' slug=article.slug %}">{{article.title}}</a></h2>
      <p>{{article.snippet}}</p>
      <p>{{article.date}}</p>
      <p class="author">added by {{ article.author.username }}</p>
    </div>
    {% endfor %}
  </div>
{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Its about</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis voluptas magnam fuga voluptate, nam repudiandae dolorum odit libero rerum accusamus quis. Et temporibus minima ea officiis modi, similique dolorum labore? Delectus maxime aut quasi minus maiores odit neque dolor illum, repudiandae officia recusandae cum architecto ducimus dolorum, veritatis repellat voluptatum!

    </p>
</body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock content%}
        </div>
    </body>
</html>